name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

#include <stdio.h>
#include <stdlib.h>
void grid(int gameMode){
    if (gameMode == 1) {                                   // Beginner Mode Grid
        char gridArray[5][5];
        printf("\t\t\t\t0   1   2   3   4");
        int k=1;                                           // Counter Of Odd Numbering
        for(int i=0 ; i<5 ; i+=2){
            switch (i) {
                case 0 :
                    printf("\n\n\n");
                    printf("\t\t\t%d",i);
                    for(int j=0 ; j<5 ; j+=2){
                    printf("\t");
                    gridArray[i][j] = 254;
                    printf("%c", gridArray[i][j] );
                    }
                    printf("\n");
                    break;
                case 2 :
                    printf("\n");
                    printf("\t\t\t%d",k);
                    k=3;
                    printf("\n\n");
                    printf("\t\t\t%d",i);
                    for(int j=0 ; j<5 ; j+=2){
                    printf("\t");
                    gridArray[i][j] = 254;
                    printf("%c", gridArray[i][j] );
                    }
                    printf("\n");
                    break;
                case 4 :
                    printf("\n");
                    printf("\t\t\t%d",k);
                    printf("\n\n");
                    printf("\t\t\t%d",i);
                    for(int j=0 ; j<5 ; j+=2){
                    printf("\t");
                    gridArray[i][j] = 254;
                    printf("%c", gridArray[i][j] );
                    }
                    printf("\n");
                    break;
                }
    }
    }
    else if(gameMode == 2) {                               // Expert Mode Grid
        char gridArray[11][11];
        printf("\t\t\t\t0   1   2   3   4   5   6   7   8   9   10");
        int k=1;                                           // Counter Of Odd Numbering
        for(int i=0 ; i<11 ; i+=2){
            switch (i) {
                case 0 :
                    printf("\n\n\n");
                    printf("\t\t\t%d",i);
                    for(int j=0 ; j<11 ; j+=2){
                    printf("\t");
                    gridArray[i][j] = 254;
                    printf("%c", gridArray[i][j] );
                    }
                    printf("\n");
                    break;
                case 2 :
                    printf("\n");
                    printf("\t\t\t%d",k);
                    k=3;
                    printf("\n\n");
                    printf("\t\t\t%d",i);
                    for(int j=0 ; j<11 ; j+=2){
                    printf("\t");
                    gridArray[i][j] = 254;
                    printf("%c", gridArray[i][j] );
                    }
                    printf("\n");
                    break;
                case 4 :
                    printf("\n");
                    printf("\t\t\t%d",k);
                    k=5;
                    printf("\n\n");
                    printf("\t\t\t%d",i);
                    for(int j=0 ; j<11 ; j+=2){
                    printf("\t");
                    gridArray[i][j] = 254;
                    printf("%c", gridArray[i][j] );
                    }
                    printf("\n");
                    break;
                case 6 :
                    printf("\n");
                    printf("\t\t\t%d",k);
                    k=7;
                    printf("\n\n");
                    printf("\t\t\t%d",i);
                    for(int j=0 ; j<11 ; j+=2){
                    printf("\t");
                    gridArray[i][j] = 254;
                    printf("%c", gridArray[i][j] );
                    }
                    printf("\n");
                    break;
                case 8 :
                    printf("\n");
                    printf("\t\t\t%d",k);
                    k=9;
                    printf("\n\n");
                    printf("\t\t\t%d",i);
                    for(int j=0 ; j<11 ; j+=2){
                    printf("\t");
                    gridArray[i][j] = 254;
                    printf("%c", gridArray[i][j] );
                    }
                    printf("\n");
                    break;
                case 10 :
                    printf("\n");
                    printf("\t\t\t%d",k);
                    printf("\n\n");
                    printf("\t\t\t%d",i);
                    for(int j=0 ; j<11 ; j+=2){
                    printf("\t");
                    gridArray[i][j] = 254;
                    printf("%c", gridArray[i][j] );
                    }
                    printf("\n");
                    break;
                }
    }
  }
}
int main()
{
    printf("Hello Gamer!\n");
    printf("Choose Mode Of The Game:\n");
    printf("*for \"Beginners\" mode press 1\n*for \"Experts\" mode press 2\n");
    int  gameMode;
    scanf("%d",&gameMode);
    grid(gameMode);
    return 0;
}


